services:
  - type: web
    name: clinic-system
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: clinic-db
          property: connectionString
    
databases:
  - name: clinic-db
    databaseName: clinic_database
    user: clinic_user
