services:
  - type: web
    name: clinic-system
    runtime: node
    plan: free
    buildCommand: cd backend && npm install && cd ../frontend && npm install && npm run build
    startCommand: cd backend && NODE_ENV=production node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: clinic-postgres
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: clinic-postgres
    plan: free
